/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ide;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Utilities;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author Yesica
 */
public class Principal extends javax.swing.JFrame {
    int re = 1;
    String nombre = "";
    int co = 0;
    int reaux = 0;
    JFileChooser seleccionado = new JFileChooser();
    File archivo;
    GestiondeArchivos gestion = new GestiondeArchivos();
    int cont = 0;
    boolean band1=false;
    JScrollPane aux1 = null ;
    
    JPanel p = new JPanel();
    String programa;
    public Principal() {
        initComponents();
       
        KeywordStyledDocument pop = new KeywordStyledDocument();//nuevo constructor
        PaneldeCodigo.setStyledDocument(pop);
        TextLineNumber lineNumber = new TextLineNumber(PaneldeCodigo);
        jScrollPane1.setRowHeaderView(lineNumber);
        renCol.setText(":");
        SaveBottom.setEnabled(false);
        SaveAsBottom.setEnabled(false);
        jMenuItem_Guardar.setEnabled(false);
        jMenuItem_GuardarC.setEnabled(false);
        jMenuItem_Cerrar.setEnabled(false);
        DeleteBottom.setEnabled(false);
        RunBottom.setEnabled(false);

    }
    //Analisis Lexico
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTabbedPane_VentanaErrores = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        errsem = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel_Botones = new javax.swing.JPanel();
        NewFileBottom = new javax.swing.JButton();
        OpenBottom = new javax.swing.JButton();
        SaveBottom = new javax.swing.JButton();
        SaveAsBottom = new javax.swing.JButton();
        ConfigButtom = new javax.swing.JButton();
        DeleteBottom = new javax.swing.JButton();
        RunBottom = new javax.swing.JButton();
        jTabbedPane_Ventana = new javax.swing.JTabbedPane();
        jPanel_lexico = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_lexico = new javax.swing.JTextArea();
        jPanel_sintactico = new javax.swing.JPanel();
        jPanel_codigo = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        CI = new javax.swing.JTextArea();
        arbolSemantico = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PaneldeCodigo = new javax.swing.JTextPane();
        renCol = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Archivo = new javax.swing.JMenu();
        jMenuItem_Nuevo = new javax.swing.JMenuItem();
        jMenuItem_Guardar = new javax.swing.JMenuItem();
        jMenuItem_GuardarC = new javax.swing.JMenuItem();
        jMenuItem_Abrir = new javax.swing.JMenuItem();
        jMenuItem_Cerrar = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu_Editar = new javax.swing.JMenu();
        jMenuItem_Color = new javax.swing.JMenuItem();
        jMenuItem_Eliminar = new javax.swing.JMenuItem();
        jMenu_Ejecutar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu_Ayuda = new javax.swing.JMenu();
        jMenuItem_Instr = new javax.swing.JMenuItem();
        jMenuItem_Acerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 350));

        jTabbedPane_VentanaErrores.setToolTipText("");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 260, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3553, Short.MAX_VALUE))
        );

        jTabbedPane_VentanaErrores.addTab("Errores Léxicos", jPanel1);

        salida.setEditable(false);
        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane8.setViewportView(salida);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 276, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3549, Short.MAX_VALUE))
        );

        jTabbedPane_VentanaErrores.addTab("Salida del Programa", jPanel2);

        errsem.setEditable(false);
        errsem.setColumns(20);
        errsem.setRows(5);
        jScrollPane4.setViewportView(errsem);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 276, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3550, Short.MAX_VALUE))
        );

        jTabbedPane_VentanaErrores.addTab("Errores Semanticos", jPanel5);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 275, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3564, Short.MAX_VALUE))
        );

        jTabbedPane_VentanaErrores.addTab("Tabla de Simbolos", jPanel6);

        jScrollPane5.setViewportView(jTabbedPane_VentanaErrores);

        NewFileBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Nfile.png"))); // NOI18N
        NewFileBottom.setToolTipText("Nuevo");
        NewFileBottom.setBorder(null);
        NewFileBottom.setBorderPainted(false);
        NewFileBottom.setContentAreaFilled(false);
        NewFileBottom.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Nfile2.png"))); // NOI18N
        NewFileBottom.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Nfile2.png"))); // NOI18N
        NewFileBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewFileBottomActionPerformed(evt);
            }
        });

        OpenBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Ofile.png"))); // NOI18N
        OpenBottom.setToolTipText("Abrir");
        OpenBottom.setBorder(null);
        OpenBottom.setBorderPainted(false);
        OpenBottom.setContentAreaFilled(false);
        OpenBottom.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Ofile2.png"))); // NOI18N
        OpenBottom.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Ofile2.png"))); // NOI18N
        OpenBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenBottomActionPerformed(evt);
            }
        });

        SaveBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/SGfile1.png"))); // NOI18N
        SaveBottom.setToolTipText("Guardar");
        SaveBottom.setBorder(null);
        SaveBottom.setBorderPainted(false);
        SaveBottom.setContentAreaFilled(false);
        SaveBottom.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/SGfile2.png"))); // NOI18N
        SaveBottom.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/SGfile2.png"))); // NOI18N
        SaveBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBottomActionPerformed(evt);
            }
        });

        SaveAsBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Sfile2.png"))); // NOI18N
        SaveAsBottom.setToolTipText("Guardar Como...");
        SaveAsBottom.setBorder(null);
        SaveAsBottom.setBorderPainted(false);
        SaveAsBottom.setContentAreaFilled(false);
        SaveAsBottom.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Sfile3.png"))); // NOI18N
        SaveAsBottom.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Sfile2.png"))); // NOI18N
        SaveAsBottom.setVerifyInputWhenFocusTarget(false);
        SaveAsBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsBottomActionPerformed(evt);
            }
        });

        ConfigButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Cfile2.png"))); // NOI18N
        ConfigButtom.setToolTipText("Configuracion");
        ConfigButtom.setBorder(null);
        ConfigButtom.setBorderPainted(false);
        ConfigButtom.setContentAreaFilled(false);
        ConfigButtom.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Cfile3.png"))); // NOI18N
        ConfigButtom.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Cfile2.png"))); // NOI18N
        ConfigButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigButtomActionPerformed(evt);
            }
        });

        DeleteBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Dfile.png"))); // NOI18N
        DeleteBottom.setToolTipText("Cerrar");
        DeleteBottom.setBorder(null);
        DeleteBottom.setBorderPainted(false);
        DeleteBottom.setContentAreaFilled(false);
        DeleteBottom.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Dfile2.png"))); // NOI18N
        DeleteBottom.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Dfile2.png"))); // NOI18N
        DeleteBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBottomActionPerformed(evt);
            }
        });

        RunBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Pfile2.png"))); // NOI18N
        RunBottom.setToolTipText("Ejecutar");
        RunBottom.setBorder(null);
        RunBottom.setBorderPainted(false);
        RunBottom.setContentAreaFilled(false);
        RunBottom.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Rfile3.png"))); // NOI18N
        RunBottom.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Pfile2.png"))); // NOI18N
        RunBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunBottomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BotonesLayout = new javax.swing.GroupLayout(jPanel_Botones);
        jPanel_Botones.setLayout(jPanel_BotonesLayout);
        jPanel_BotonesLayout.setHorizontalGroup(
            jPanel_BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BotonesLayout.createSequentialGroup()
                .addComponent(SaveBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SaveAsBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OpenBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewFileBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfigButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RunBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BotonesLayout.setVerticalGroup(
            jPanel_BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SaveBottom, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
            .addComponent(SaveAsBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(OpenBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NewFileBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DeleteBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ConfigButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RunBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextArea_lexico.setEditable(false);
        jTextArea_lexico.setColumns(20);
        jTextArea_lexico.setRows(5);
        jScrollPane3.setViewportView(jTextArea_lexico);

        javax.swing.GroupLayout jPanel_lexicoLayout = new javax.swing.GroupLayout(jPanel_lexico);
        jPanel_lexico.setLayout(jPanel_lexicoLayout);
        jPanel_lexicoLayout.setHorizontalGroup(
            jPanel_lexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        jPanel_lexicoLayout.setVerticalGroup(
            jPanel_lexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        jTabbedPane_Ventana.addTab("Léxico", jPanel_lexico);

        javax.swing.GroupLayout jPanel_sintacticoLayout = new javax.swing.GroupLayout(jPanel_sintactico);
        jPanel_sintactico.setLayout(jPanel_sintacticoLayout);
        jPanel_sintacticoLayout.setHorizontalGroup(
            jPanel_sintacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );
        jPanel_sintacticoLayout.setVerticalGroup(
            jPanel_sintacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        jTabbedPane_Ventana.addTab("Sintáctico", jPanel_sintactico);

        CI.setEditable(false);
        CI.setColumns(20);
        CI.setRows(5);
        jScrollPane6.setViewportView(CI);

        javax.swing.GroupLayout jPanel_codigoLayout = new javax.swing.GroupLayout(jPanel_codigo);
        jPanel_codigo.setLayout(jPanel_codigoLayout);
        jPanel_codigoLayout.setHorizontalGroup(
            jPanel_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        jPanel_codigoLayout.setVerticalGroup(
            jPanel_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        jTabbedPane_Ventana.addTab("Código Intermedio", jPanel_codigo);

        javax.swing.GroupLayout arbolSemanticoLayout = new javax.swing.GroupLayout(arbolSemantico);
        arbolSemantico.setLayout(arbolSemanticoLayout);
        arbolSemanticoLayout.setHorizontalGroup(
            arbolSemanticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );
        arbolSemanticoLayout.setVerticalGroup(
            arbolSemanticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        jTabbedPane_Ventana.addTab("Semántica", arbolSemantico);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setToolTipText("");

        PaneldeCodigo.setMaximumSize(new java.awt.Dimension(800, 500));
        PaneldeCodigo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                PaneldeCodigoCaretUpdate(evt);
            }
        });
        PaneldeCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PaneldeCodigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PaneldeCodigoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(PaneldeCodigo);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jMenu_Archivo.setText("Archivo");

        jMenuItem_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/Rnew.png"))); // NOI18N
        jMenuItem_Nuevo.setText("Nuevo Archivo");
        jMenuItem_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NuevoActionPerformed(evt);
            }
        });
        jMenu_Archivo.add(jMenuItem_Nuevo);

        jMenuItem_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ide/SGfile0.png"))); // NOI18N
        jMenuItem_Guardar.setText("Guardar");
        jMenuItem_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GuardarActionPerformed(evt);
            }
        });
        jMenu_Archivo.add(jMenuItem_Guardar);

        jMenuItem_GuardarC.setText("Guardar Como...");
        jMenuItem_GuardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GuardarCActionPerformed(evt);
            }
        });
        jMenu_Archivo.add(jMenuItem_GuardarC);

        jMenuItem_Abrir.setText("Abrir Archivo");
        jMenuItem_Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AbrirActionPerformed(evt);
            }
        });
        jMenu_Archivo.add(jMenuItem_Abrir);

        jMenuItem_Cerrar.setText("Cerrar Archivo");
        jMenuItem_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CerrarActionPerformed(evt);
            }
        });
        jMenu_Archivo.add(jMenuItem_Cerrar);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu_Archivo.add(jMenuItem4);

        jMenuBar1.add(jMenu_Archivo);

        jMenu_Editar.setText("Editar");

        jMenuItem_Color.setText("Color de Texto");
        jMenu_Editar.add(jMenuItem_Color);

        jMenuItem_Eliminar.setText("Eliminar");
        jMenuItem_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_EliminarActionPerformed(evt);
            }
        });
        jMenu_Editar.add(jMenuItem_Eliminar);

        jMenuBar1.add(jMenu_Editar);

        jMenu_Ejecutar.setText("Ejecutar");

        jMenuItem1.setText("Ejecutar Archivo");
        jMenu_Ejecutar.add(jMenuItem1);

        jMenuItem2.setText("Compilar Archivo");
        jMenu_Ejecutar.add(jMenuItem2);

        jMenuBar1.add(jMenu_Ejecutar);

        jMenu_Ayuda.setText("Ayuda");

        jMenuItem_Instr.setText("Instrucciones");
        jMenuItem_Instr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_InstrActionPerformed(evt);
            }
        });
        jMenu_Ayuda.add(jMenuItem_Instr);

        jMenuItem_Acerca.setText("Acerca de...");
        jMenuItem_Acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AcercaActionPerformed(evt);
            }
        });
        jMenu_Ayuda.add(jMenuItem_Acerca);

        jMenuBar1.add(jMenu_Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane_Ventana)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(renCol, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane_Ventana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renCol, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_EliminarActionPerformed

    private void OpenBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenBottomActionPerformed
        if (seleccionado.showDialog(this, "Abrir Archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionado.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("txt")) {
                    String contenido = gestion.AbrirArchivo(archivo);
                    PaneldeCodigo.setText(contenido);
                    nombre = archivo.getName();
                    int re = PaneldeCodigo.getCaretPosition();
                    PaneldeCodigo.setCaretPosition(0);
                    PaneldeCodigo.setCaretPosition(re);
                    RunBottom.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "No es posible abrir archivo");
                }
            }
        }

    }//GEN-LAST:event_OpenBottomActionPerformed

    private void SaveAsBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsBottomActionPerformed
        if (seleccionado.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionado.getSelectedFile();
            System.out.println("nombre: " + archivo.getName());
            nombre = archivo.getName();
            if (archivo.getName().endsWith("txt")) {
                String contenido = PaneldeCodigo.getText();
                String respuesta = gestion.GuardarArchivoComo(archivo, contenido);
                nombre.lastIndexOf("\\");
                if (respuesta != null) {
                    JOptionPane.showMessageDialog(null, respuesta);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Guardad Archivo");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El texto esta en un formato Equivocado");
            }
        }

    }//GEN-LAST:event_SaveAsBottomActionPerformed

    private void SaveBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBottomActionPerformed
        if (nombre.equals("")) {
            if (seleccionado.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
                archivo = seleccionado.getSelectedFile();
                System.out.println("nombre: " + archivo.getName());

                if (archivo.getName().endsWith("txt")) {
                    String contenido = PaneldeCodigo.getText();
                    String respuesta = gestion.GuardarArchivoComo(archivo, contenido);
                    nombre.lastIndexOf("\\");//                         quita el texto al guardar por primera vez
                    if (respuesta != null) {
                        JOptionPane.showMessageDialog(null, respuesta);
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al Guardad Archivo");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El texto esta en un formato Equivocado");
                }
            }
        } else {
            SaveBottom.setEnabled(false);
            gestion.guardar(archivo, PaneldeCodigo);
        }
    }//GEN-LAST:event_SaveBottomActionPerformed

    private void jMenuItem_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CerrarActionPerformed
        gestion.cerrar();
        gestion.guardar(archivo, PaneldeCodigo);
        gestion.limpiar(PaneldeCodigo);
    }//GEN-LAST:event_jMenuItem_CerrarActionPerformed

    private void PaneldeCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaneldeCodigoKeyPressed

    }//GEN-LAST:event_PaneldeCodigoKeyPressed

    private void jMenuItem_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NuevoActionPerformed
        nombre = "";
        gestion.limpiar(PaneldeCodigo);
        PaneldeCodigo.setCaretPosition(PaneldeCodigo.getStyledDocument().getLength());
    }//GEN-LAST:event_jMenuItem_NuevoActionPerformed

    private void PaneldeCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaneldeCodigoKeyReleased

        PaneldeCodigo.setAutoscrolls(true);
        if (evt.getKeyCode() == evt.VK_BACK_SPACE | evt.getKeyCode() == evt.VK_ENTER | evt.getKeyCode() == evt.VK_DELETE
                | evt.getKeyCode() == evt.VK_V | evt.getKeyCode() == evt.VK_X) {

            int re = PaneldeCodigo.getCaretPosition();
            PaneldeCodigo.setCaretPosition(0);
            PaneldeCodigo.setCaretPosition(re);

        }
        if (PaneldeCodigo.getText().length() != 0) {
            SaveBottom.setEnabled(true);
            SaveAsBottom.setEnabled(true);
            jMenuItem_Guardar.setEnabled(true);
            jMenuItem_GuardarC.setEnabled(true);
            jMenuItem_Cerrar.setEnabled(true);
            DeleteBottom.setEnabled(true);
            RunBottom.setEnabled(true);
        }


    }//GEN-LAST:event_PaneldeCodigoKeyReleased

    private void NewFileBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewFileBottomActionPerformed
        //crea uu nuevo archivo de texto
        nombre = "";
        gestion.limpiar(PaneldeCodigo);
        PaneldeCodigo.setCaretPosition(PaneldeCodigo.getStyledDocument().getLength());
    }//GEN-LAST:event_NewFileBottomActionPerformed

    private void DeleteBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBottomActionPerformed

        gestion.limpiar(PaneldeCodigo);

    }//GEN-LAST:event_DeleteBottomActionPerformed

    private void jMenuItem_AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AbrirActionPerformed
        //Abre el archivo de texto 
        if (seleccionado.showDialog(this, "Abrir Archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionado.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("txt")) {
                    String contenido = gestion.AbrirArchivo(archivo);
                    PaneldeCodigo.setText(contenido);
                    int re = PaneldeCodigo.getCaretPosition();
                    PaneldeCodigo.setCaretPosition(0);
                    PaneldeCodigo.setCaretPosition(re);
                } else {
                    JOptionPane.showMessageDialog(null, "No es posible abrir archivo");
                }
            }
        }

    }//GEN-LAST:event_jMenuItem_AbrirActionPerformed

    private void jMenuItem_GuardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GuardarCActionPerformed
        //Guarda el texto
        if (seleccionado.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionado.getSelectedFile();
            if (archivo.getName().endsWith("txt")) {
                String contenido = PaneldeCodigo.getText();
                String respuesta = gestion.GuardarArchivoComo(archivo, contenido);
                if (respuesta != null) {
                    JOptionPane.showMessageDialog(null, respuesta);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Guardad Archivo");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El texto esta en un formato Equivocado");
            }
        }

    }//GEN-LAST:event_jMenuItem_GuardarCActionPerformed

    private void PaneldeCodigoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_PaneldeCodigoCaretUpdate
        //Lee el archivo de texto en el panel
        try {
            int caretpos = PaneldeCodigo.getCaretPosition();
            int rowNum = (caretpos == 0) ? 1 : 0;
            int coaux = 0;
            for (int offset = caretpos; offset > 0;) {
                offset = Utilities.getRowStart(PaneldeCodigo, offset) - 1;
                rowNum++;
            }
            //reaux = PaneldeCodigo.getSelectionEnd();// .getLineOfOffset(caretpos);
            int startrow = (Utilities.getRowStart(PaneldeCodigo, caretpos) - 1);
            int numOffsets = rowNum - 1;
            coaux = (caretpos == 0) ? 1 : (caretpos - numOffsets) - (startrow - numOffsets);
            //reaux += 1;
            renCol.setText(rowNum + ":" + coaux);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_PaneldeCodigoCaretUpdate

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem_AcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AcercaActionPerformed
        AcercaDe AcercaDe = new AcercaDe(this, rootPaneCheckingEnabled);
        AcercaDe.setVisible(true);
    }//GEN-LAST:event_jMenuItem_AcercaActionPerformed

    private void jMenuItem_InstrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_InstrActionPerformed
        //informacion de Ruby
        String texto = "Instrucciones\n"
                + "Las instrucciones que se dan para el correcto uso de este IDE son "
                + "los elementos de programa que controlan cómo y en qué orden se "
                + "manipulan los objetos. Esta sección incluye Información general\n"
                + "Instrucciones de expresión. Estas instrucciones evalúan una expresión para ver sus "
                + "efectos secundarios o para averiguar su valor devuelto.\n"
                + "Instrucciones NULL. Estas instrucciones se pueden proporcionar "
                + "cuando la sintaxis de C++ requiere una instrucción pero no se va "
                + "a realizar ninguna acción.\n"
                + "Instrucciones compuestas. Estas instrucciones son grupos de instrucciones "
                + "entre llaves ({}). Se pueden utilizar donde se puede utilizar una sola instrucción.\n"
                + "Instrucciones de selección. Estas instrucciones realizan una prueba; a continuación, "
                + "ejecutan una sección de código si la prueba se evalúa como true (distinto de cero). "
                + "Pueden ejecutar otra sección de código si la prueba se evalúa como false.\n"
                + "Instrucciones de iteración. Estas instrucciones ejecutan repetidamente un bloque de código hasta que "
                + "se cumple un criterio de finalización especificado.\n"
                + "Instrucciones de salto. Estas instrucciones transfieren el control inmediatamente "
                + "a otra ubicación de la función o devuelven el control de la función.\n"
                + "Instrucciones de declaración. Las declaraciones introducen un nombre en un programa. "
                + "(En Declaraciones se proporciona información más detallada sobre las declaraciones).";

        JTextArea text = new JTextArea(texto);
        text.setEditable(false);
        text.setColumns(30);
        text.setLineWrap(true);
        text.setWrapStyleWord(true);
        text.setSize(text.getPreferredSize().width, 5);
        //text.enable(false);
        text.setCaretColor(Color.MAGENTA);
        JOptionPane.showMessageDialog(null, new JScrollPane(text), "Instrucciones", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem_InstrActionPerformed

    private void jMenuItem_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GuardarActionPerformed
        // Guarda el etxto en el achivo que se definira si no existe, y si ya existe solo lo guasrda
        if (nombre.equals("")) {
            if (seleccionado.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
                archivo = seleccionado.getSelectedFile();
                System.out.println("nombre: " + archivo.getName());

                if (archivo.getName().endsWith("txt")) {
                    String contenido = PaneldeCodigo.getText();
                    String respuesta = gestion.GuardarArchivoComo(archivo, contenido);
                    nombre.lastIndexOf("\\");//                         quita el texto al guardar por primera vez
                    if (respuesta != null) {
                        JOptionPane.showMessageDialog(null, respuesta);
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al Guardad Archivo");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El texto esta en un formato Equivocado");
                }
            }
        } else {

            gestion.guardar(archivo, PaneldeCodigo);
        }
    }//GEN-LAST:event_jMenuItem_GuardarActionPerformed

    private void ConfigButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfigButtomActionPerformed

    private void RunBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunBottomActionPerformed
        // TODO add your handling code here:
        gestion.guardar(archivo, PaneldeCodigo);
        this.jTextArea_lexico.setText(" ");
        this.jTextArea1.setText(" ");
        this.salida.setText(" ");
        System.out.println("Compilando");
        File f;
        //guarda siempre por dafault el programa en un archivo, para este archivo mandarlo a ruby
        f = new File("lexico.txt");
        try {
            FileWriter w = new FileWriter(f);
            BufferedWriter bw = new BufferedWriter(w);
            PrintWriter wr = new PrintWriter(bw);
            wr.write(PaneldeCodigo.getText());
            wr.close();
            bw.close();
        } catch (IOException e) {
            e.printStackTrace();
        };
        
        //Ejecuta el archivo ruby
        try {
            
            String env = System.getenv("DOCKER_HOME");
            System.out.println(env);
            Process r = Runtime.getRuntime().exec("cmd /C docker-compose -f "+ env +"\\docker-compose.yml up ");
            BufferedReader in = new BufferedReader(new InputStreamReader(r.getInputStream()));
            String line = null;
            while ((line = in.readLine()) != null) {
                System.out.println(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        //Muestra Archivo de Tokens  
        File arch = new File("tokens.txt");
        try {
            BufferedReader leer = new BufferedReader(new FileReader(arch));
            String linea = leer.readLine();
            while (linea != null) {
                jTextArea_lexico.append(linea + "\n");
                linea = leer.readLine();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //muestra el archivo de errores
        File arch1 = new File("errores.txt");
        try {
            BufferedReader leer1 = new BufferedReader(new FileReader(arch1));
            String linea1 = leer1.readLine();
            while (linea1 != null) {
                jTextArea1.append(linea1 + "\n");
                linea1 = leer1.readLine();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* 
        Arbol_Sin.setText("");
        //muestra arbol sintactico sin desplegar
        File arch2 = new File("sintactico.txt");
        try {
            BufferedReader leer = new BufferedReader(new FileReader(arch2));
            String linea = leer.readLine();
            System.out.println("*"+linea);
            while (linea != null) {
                 System.out.println("->"+linea);
                Arbol_Sin.append(linea + "\n");
                linea = leer.readLine();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        //TABLA HASH
        File semanArch = null;
        FileReader fileR=null;
        BufferedReader buffR = null;
        Vector cabeceras = new Vector();
        try{
            semanArch = new File("hash.txt");
            fileR = new FileReader(semanArch);
            buffR = new BufferedReader(fileR);
            String lineSeman;
           // DefaultListModel lista = new DefaultListModel();
            DefaultTableModel tabla = new DefaultTableModel();
            tabla.addColumn("Nombre");
            tabla.addColumn("Localidad");
            tabla.addColumn("Valor");
            tabla.addColumn("Tipo");
            tabla.addColumn("Lineas");
            while((lineSeman=buffR.readLine())!=null)
            {
                StringTokenizer cadSeman = new StringTokenizer(lineSeman,"|");
                Vector vecSeman = new Vector();
                while(cadSeman.hasMoreTokens())
                {
                    vecSeman.addElement(cadSeman.nextToken());
                }
                tabla.addRow(vecSeman);
                System.out.println(lineSeman);
                //lista.addElement(line);
                //tabla.addRow(new String[]{line});
            }
            jTable2.setModel(tabla);
        }catch(Exception e){
        }
        finally{
            try{
                if(null!=fileR){
                    fileR.close();
                }
            }catch(Exception e2){
                
            }
        }

        System.out.println("COMENZANDO______________________________________________________");
            //panArb = tr.crearArbol();
          TreeFromTextFileDemo tr = new TreeFromTextFileDemo();
         jPanel_sintactico = tr.crearArbol("sintactico.txt");
          jTabbedPane_Ventana.setComponentAt(1, jPanel_sintactico);
          
        TreeFromTextFileDemo tr2 = new TreeFromTextFileDemo();
          arbolSemantico = tr2.crearArbol("semantico.txt");
          jTabbedPane_Ventana.setComponentAt(3, arbolSemantico);
        
        //jTabbedPane_Ventana.setComponentAt(4, );
        System.out.println("REVELANDO_________________________________________________________");
        //muestra el archivo de errores sintacticos
        File arch3 = new File("erroresS.txt");
        try {
            BufferedReader leer1 = new BufferedReader(new FileReader(arch3));
            String linea1 = leer1.readLine();
            
                
            while (linea1 != null) {
               
                salida.append(linea1 + "\n");
                linea1 = leer1.readLine();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //ERRORES SEMANTICOS
        errsem.setText("");
         File arch4 = new File("erroreSem.txt");
        try {
            BufferedReader leer2 = new BufferedReader(new FileReader(arch4));
            String linea2 = leer2.readLine();
            
                
            while (linea2 != null) {
               
                errsem.append(linea2 + "\n");
                linea2 = leer2.readLine();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //sintactico*******************************************************************************
        //arbol_Desp(2);
        // Generacion de codigo intermedio y resultados
        //Muestra Archivo de Tokens  
        System.out.println("Generando codigo intermedio *******************O****OO****");
        File arch5 = new File("code_interm.txt");
        try {
            BufferedReader leer = new BufferedReader(new FileReader(arch5));
            String linea = leer.readLine();
            while (linea != null) {
                CI.append(linea + "\n");
                linea = leer.readLine();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Generando Resultados ||||||||||||||||||||||||||||||||||||||||||||||||");
        File arch6 = new File("result.txt");
        try {
            BufferedReader leer = new BufferedReader(new FileReader(arch6));
            String linea = leer.readLine();
            while (linea != null) {
                salida.append(linea + "\n");
                linea = leer.readLine();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("En toeria ya termino");
    }//GEN-LAST:event_RunBottomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CI;
    private javax.swing.JButton ConfigButtom;
    private javax.swing.JButton DeleteBottom;
    private javax.swing.JButton NewFileBottom;
    private javax.swing.JButton OpenBottom;
    private javax.swing.JTextPane PaneldeCodigo;
    private javax.swing.JButton RunBottom;
    private javax.swing.JButton SaveAsBottom;
    private javax.swing.JButton SaveBottom;
    private javax.swing.JPanel arbolSemantico;
    private javax.swing.JTextArea errsem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem_Abrir;
    private javax.swing.JMenuItem jMenuItem_Acerca;
    private javax.swing.JMenuItem jMenuItem_Cerrar;
    private javax.swing.JMenuItem jMenuItem_Color;
    private javax.swing.JMenuItem jMenuItem_Eliminar;
    private javax.swing.JMenuItem jMenuItem_Guardar;
    private javax.swing.JMenuItem jMenuItem_GuardarC;
    private javax.swing.JMenuItem jMenuItem_Instr;
    private javax.swing.JMenuItem jMenuItem_Nuevo;
    private javax.swing.JMenu jMenu_Archivo;
    private javax.swing.JMenu jMenu_Ayuda;
    private javax.swing.JMenu jMenu_Editar;
    private javax.swing.JMenu jMenu_Ejecutar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_Botones;
    private javax.swing.JPanel jPanel_codigo;
    private javax.swing.JPanel jPanel_lexico;
    private javax.swing.JPanel jPanel_sintactico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane_Ventana;
    private javax.swing.JTabbedPane jTabbedPane_VentanaErrores;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea_lexico;
    private javax.swing.JLabel renCol;
    private javax.swing.JTextArea salida;
    // End of variables declaration//GEN-END:variables
}
